name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy-order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Order Service to Cloud Run
        run: |
          gcloud run deploy order-service \
            --image gcr.io/$PROJECT_ID/order-service \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

  deploy-inventory-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Inventory Service to Cloud Run
        run: |
          gcloud run deploy inventory-service \
            --image gcr.io/$PROJECT_ID/inventory-service \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
